import { useEffect, useMemo, useRef, useState } from 'react'
import { addDays, average, bmi, compliance, currentStreak, dateFromKey, dateKey, fastingGoal, feedback, fmtDate, fmtNum, latestLog, planMonth, weekStart } from './data'
import { backup, loadData } from './storage'
import { emptyLog, type DailyLog, type RefinedCarbs, type AppSettings } from './types'
import { api } from './api'

type Page = 'dashboard' | 'log' | 'history' | 'review' | 'plan' | 'rules'
const pages: Array<[Page, string, string]> = [['dashboard', 'Dashboard', '⌂'], ['log', 'Daily log', '＋'], ['history', 'History', '◫'], ['review', 'Weekly review', '◷'], ['plan', 'Plan', '◎'], ['rules', 'Rules', '✓']]
const toNum = (value: string) => value === '' ? null : Number(value)
const download = (name: string, type: string, content: string) => { const url = URL.createObjectURL(new Blob([content], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url) }
const csvValue = (value: unknown) => `"${String(value ?? '').replaceAll('"', '""')}"`
const csvColumns: (keyof DailyLog)[] = ['id', 'date', 'weightKg', 'eatingWindowStart', 'eatingWindowEnd', 'fastingHours', 'firstMeal', 'secondMeal', 'snacks', 'lateNightEating', 'sugaryDrink', 'refinedCarbs', 'exerciseType', 'exerciseMinutes', 'sleepHours', 'hungerLevel', 'energyLevel', 'moodLevel', 'notes', 'biggestProblem', 'tomorrowFocus', 'createdAt', 'updatedAt']

function App() {
  const legacy = useMemo(loadData, [])
  const [settings, setSettings] = useState(legacy.settings)
  const [logs, setLogs] = useState<DailyLog[]>([])
  const [page, setPage] = useState<Page>('dashboard')
  const [notice, setNotice] = useState('')
  const [auth, setAuth] = useState<'checking' | 'out' | 'in'>('checking')
  const [migrationAvailable, setMigrationAvailable] = useState(false)

  const loadRemote = async () => { const data = await api.data(); setSettings(data.settings); setLogs(data.logs); setMigrationAvailable(data.logs.length === 0 && legacy.logs.length > 0) }
  useEffect(() => { api.session().then(async ({ authenticated }) => { if (authenticated) { await loadRemote(); setAuth('in') } else setAuth('out') }).catch(() => setAuth('out')) }, [])
  const ordered = useMemo(() => [...logs].sort((a, b) => b.date.localeCompare(a.date)), [logs])
  const navigate = (next: Page) => { setPage(next); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const saveLog = async (entry: DailyLog) => { const saved = await api.log(entry); setLogs((items) => { const i = items.findIndex((item) => item.date === saved.date); return i >= 0 ? items.map((item, index) => index === i ? saved : item) : [...items, saved] }); setNotice('Daily log saved.') }
  const remove = async (id: string) => { if (window.confirm('Delete this daily log?')) { await api.deleteLog(id); setLogs((items) => items.filter((item) => item.id !== id)); setNotice('Daily log deleted.') } }
  const importLogs = async (entries: DailyLog[], mode: 'merge' | 'replace', incomingSettings?: AppSettings) => { const data = await api.import({ settings: incomingSettings ?? settings, logs: entries }, mode); setSettings(data.settings); setLogs(data.logs); setMigrationAvailable(false); setNotice(`${entries.length} record${entries.length === 1 ? '' : 's'} imported.`) }
  const saveSettings = async (next: AppSettings) => { setSettings(next); try { await api.settings(next) } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not save settings.') } }
  const logout = async () => { await api.logout(); setAuth('out'); setLogs([]); setNotice('') }
  const migrate = async () => { await importLogs(legacy.logs, 'merge', legacy.settings); setNotice('Your existing browser records were moved to MongoDB.') }

  if (auth === 'checking') return <div className="grid min-h-screen place-items-center bg-[#f6f7f3] text-slate-600">Loading Weight Path…</div>
  if (auth === 'out') return <Login onLogin={async (password) => { await api.login(password); await loadRemote(); setAuth('in') }} />

  return <div className="min-h-screen bg-[#f6f7f3] text-slate-800">
    <header className="sticky top-0 z-30 border-b border-emerald-950/10 bg-[#f6f7f3]/95 backdrop-blur">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3">
        <button onClick={() => navigate('dashboard')} className="flex items-center gap-2 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-700 text-lg text-white">W</span><span><b className="block leading-none">Weight Path</b><small className="text-slate-500">Private daily tracker</small></span></button>
        <div className="flex items-center gap-2"><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-800">MongoDB synced</span><button className="text-xs font-semibold text-slate-500 hover:text-slate-900" onClick={logout}>Log out</button></div>
      </div>
      <nav className="scrollbar-none mx-auto flex max-w-6xl gap-1 overflow-x-auto px-3 pb-2" aria-label="Main navigation">{pages.map(([id, label, icon]) => <button key={id} onClick={() => navigate(id)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-medium ${page === id ? 'bg-emerald-700 text-white' : 'text-slate-600 hover:bg-emerald-100'}`}><span className="mr-1.5">{icon}</span>{label}</button>)}</nav>
    </header>
      <main className="mx-auto max-w-6xl px-4 py-6 pb-24">
      {location.protocol === 'http:' && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900"><b>Insecure connection:</b> this direct HTTP deployment does not encrypt your password or health data. Use a trusted network only.</div>}
      {migrationAvailable && <div className="mb-5 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900"><span>Daily logs found in this browser from the old local-only app.</span><button className="btn-secondary" onClick={() => void migrate()}>Move them to MongoDB</button></div>}
      {notice && <div className="mb-5 flex items-center justify-between rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900"><span>{notice}</span><button onClick={() => setNotice('')} aria-label="Close">×</button></div>}
      {page === 'dashboard' && <Dashboard logs={ordered} settings={settings} onLog={() => navigate('log')} />}
      {page === 'log' && <LogForm logs={logs} onSave={saveLog} />}
      {page === 'history' && <History logs={ordered} settings={settings} onEdit={(log) => { navigate('log'); window.setTimeout(() => window.dispatchEvent(new CustomEvent('edit-log', { detail: log })), 0) }} onDelete={remove} onImport={importLogs} />}
      {page === 'review' && <WeeklyReview logs={logs} settings={settings} />}
      {page === 'plan' && <Plan settings={settings} onSettings={saveSettings} />}
      {page === 'rules' && <Rules />}
    </main>
    <footer className="border-t border-slate-200 bg-white px-4 py-5 text-center text-xs leading-relaxed text-slate-500">This app is for personal tracking only and is not medical advice. If you have diabetes, use insulin, take glucose-lowering medication, have an eating disorder history, or feel dizzy or unwell during fasting, talk to a doctor.</footer>
  </div>
}

function Login({ onLogin }: { onLogin: (password: string) => Promise<void> }) { const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { await onLogin(password) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not log in.') } finally { setBusy(false) } }; return <main className="grid min-h-screen place-items-center bg-[#f6f7f3] p-4"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid h-12 w-12 place-items-center rounded-xl bg-emerald-700 text-xl text-white">W</div><h1 className="mt-4 text-2xl font-bold">Weight Path</h1><p className="mt-1 text-sm text-slate-500">Enter your private app password.</p><label className="mt-5 block"><span className="field-label">Password</span><input autoFocus type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}<button className="btn mt-5 w-full" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</button><p className="mt-4 text-xs text-red-700">This server uses direct HTTP, so do not use this password on any other service.</p></form></main> }

function SectionTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1>{subtitle && <p className="mt-1 text-sm text-slate-500">{subtitle}</p>}</div>{action}</div> }
function Stat({ label, value, hint, tone = 'plain' }: { label: string; value: string; hint?: string; tone?: 'plain' | 'green' | 'blue' | 'amber' }) { const bg = { plain: 'bg-white', green: 'bg-emerald-50', blue: 'bg-sky-50', amber: 'bg-amber-50' }[tone]; return <div className={`rounded-2xl border border-slate-200 p-4 shadow-sm ${bg}`}><p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p>{hint && <p className="mt-1 text-xs text-slate-500">{hint}</p>}</div> }

function Dashboard({ logs, settings, onLog }: { logs: DailyLog[]; settings: AppSettings; onLog: () => void }) {
  const latest = latestLog(logs); const weight = latest?.weightKg ?? settings.startingWeightKg; const goal = fastingGoal(settings)
  const today = new Date(); const sevenAgo = dateKey(addDays(today, -6)); const thirtyAgo = dateKey(addDays(today, -29))
  const recent = logs.filter((l) => l.date >= sevenAgo); const month = [...logs].filter((l) => l.date >= thirtyAgo && l.weightKg != null).sort((a, b) => a.date.localeCompare(b.date))
  const progress = Math.max(0, Math.min(100, ((settings.startingWeightKg - weight) / (settings.startingWeightKg - settings.targetHighKg)) * 100))
  const delta = month.length >= 2 ? month[month.length - 1].weightKg! - month[0].weightKg! : null
  const thisWeek = logs.filter((l) => l.date >= dateKey(weekStart(today)) && l.date <= dateKey(addDays(weekStart(today), 6)))
  return <>
    <SectionTitle title="Your dashboard" subtitle={latest ? `Last weight entry: ${fmtDate(latest.date)}` : 'Start with a quick daily log.'} action={<button className="btn" onClick={onLog}>+ Log today</button>} />
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="Current weight" value={`${fmtNum(weight)} kg`} hint={`Start: ${settings.startingWeightKg} kg`} tone="green" /><Stat label="Weight lost" value={`${fmtNum(settings.startingWeightKg - weight)} kg`} hint="From your start" /><Stat label="BMI" value={fmtNum(bmi(weight, settings.heightCm))} hint="Based on 176 cm" /><Stat label="Target" value="92–96 kg" hint={`${Math.round(progress)}% to 96 kg`} tone="blue" /></div>
    <div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="7-day average" value={`${fmtNum(average(recent.map((l) => l.weightKg)))} kg`} /><Stat label="30-day trend" value={delta == null ? '—' : `${delta > 0 ? '+' : ''}${fmtNum(delta)} kg`} hint="First to latest weight" tone={delta != null && delta <= 0 ? 'green' : 'amber'} /><Stat label="Fasting streak" value={`${currentStreak(logs, goal)} days`} hint={`Goal: ${goal}+ hours`} /><Stat label="This week" value={compliance(thisWeek, goal) == null ? '—' : `${compliance(thisWeek, goal)}%`} hint="Compliance score" tone="green" /></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><ChartCard title="Weight trend" subtitle="Your last 30 days" empty={!month.length}><LineChart points={month.map((l) => ({ label: fmtDate(l.date), value: l.weightKg! }))} unit="kg" /></ChartCard><ChartCard title="Fasting hours" subtitle="Your recent daily fasting" empty={!recent.length}><BarChart points={[...recent].sort((a,b) => a.date.localeCompare(b.date)).map((l) => ({ label: fmtDate(l.date), value: l.fastingHours ?? 0 }))} /></ChartCard></div>
    <div className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-start gap-3"><span className="text-xl">◎</span><div><h2 className="font-semibold text-emerald-950">Today’s simple target</h2><p className="mt-1 text-sm text-emerald-900">Aim for a {goal}+ hour fast, no sugary drinks, and a satisfying protein-and-vegetable meal. Small consistent days count.</p></div></div></div>
  </>
}
function ChartCard({ title, subtitle, empty, children }: { title: string; subtitle: string; empty: boolean; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold">{title}</h2><p className="mb-4 text-xs text-slate-500">{subtitle}</p>{empty ? <div className="grid h-52 place-items-center rounded-xl bg-slate-50 text-center text-sm text-slate-500">No data yet.<br />Your chart will appear after you log a day.</div> : children}</section> }
function LineChart({ points, unit }: { points: { label: string; value: number }[]; unit: string }) { const values = points.map((p) => p.value); const min = Math.min(...values) - .4; const max = Math.max(...values) + .4; const width = 500; const height = 210; const x = (i: number) => points.length === 1 ? width / 2 : (i / (points.length - 1)) * width; const y = (value: number) => height - ((value - min) / (max - min || 1)) * (height - 28) - 14; const path = points.map((p, i) => `${i ? 'L' : 'M'}${x(i)},${y(p.value)}`).join(' '); return <div><svg viewBox={`0 0 ${width} ${height}`} className="h-52 w-full overflow-visible" role="img" aria-label="Weight line chart"><line x1="0" x2={width} y1={height - 14} y2={height - 14} stroke="#cbd5e1" /><path d={path} fill="none" stroke="#16724f" strokeWidth="3" strokeLinecap="round" />{points.map((p, i) => <circle key={p.label} cx={x(i)} cy={y(p.value)} r="4" fill="#16724f"><title>{p.label}: {p.value} {unit}</title></circle>)}</svg><div className="flex justify-between text-xs text-slate-500"><span>{points[0]?.label}</span><span>{points.at(-1)?.label}</span></div></div> }
function BarChart({ points }: { points: { label: string; value: number }[] }) { const width = 500; const height = 210; const max = Math.max(20, ...points.map((p) => p.value)); const bar = width / points.length; return <div><svg viewBox={`0 0 ${width} ${height}`} className="h-52 w-full" role="img" aria-label="Fasting hours chart"><line x1="0" x2={width} y1={height - 14} y2={height - 14} stroke="#cbd5e1" />{points.map((p, i) => { const h = Math.max(2, (p.value / max) * (height - 28)); return <rect key={p.label} x={i * bar + bar * .15} y={height - 14 - h} width={bar * .7} height={h} rx="4" fill={p.value >= 16 ? '#16724f' : '#84bda9'}><title>{p.label}: {p.value} hours</title></rect> })}</svg><div className="flex justify-between text-xs text-slate-500"><span>{points[0]?.label}</span><span>{points.at(-1)?.label}</span></div></div> }

function LogForm({ logs, onSave }: { logs: DailyLog[]; onSave: (log: DailyLog) => Promise<void> }) {
  const [form, setForm] = useState<DailyLog>(() => logs.find((x) => x.date === dateKey(new Date())) ?? emptyLog())
  const [messages, setMessages] = useState<{ kind: 'good' | 'warn'; text: string }[]>([])
  useEffect(() => { const handler = (e: Event) => { const log = (e as CustomEvent<DailyLog>).detail; setForm(log); setMessages([]) }; window.addEventListener('edit-log', handler); return () => window.removeEventListener('edit-log', handler) }, [])
  const update = <K extends keyof DailyLog>(key: K, value: DailyLog[K]) => setForm((old) => ({ ...old, [key]: value }))
  const submit = async (e: React.FormEvent) => { e.preventDefault(); if (!form.date) return; const now = new Date().toISOString(); const existing = logs.find((l) => l.date === form.date); const saved = { ...form, id: existing?.id ?? form.id, createdAt: existing?.createdAt ?? form.createdAt, updatedAt: now }; try { await onSave(saved); setForm(saved); setMessages(feedback(saved)) } catch (error) { window.alert(error instanceof Error ? error.message : 'Could not save your log.') } }
  const Field = ({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) => <label className={wide ? 'sm:col-span-2' : ''}><span className="field-label">{label}</span>{children}</label>
  return <><SectionTitle title="Daily log" subtitle="Track honestly, not perfectly. One entry per day." /><form onSubmit={submit} className="space-y-5"><section className="form-card"><div className="grid gap-4 sm:grid-cols-2"><Field label="Date"><input type="date" value={form.date} onChange={(e) => update('date', e.target.value)} required /></Field><Field label="Morning weight (kg)"><input type="number" min="30" max="300" step="0.1" value={form.weightKg ?? ''} onChange={(e) => update('weightKg', toNum(e.target.value))} placeholder="Example: 109.5" /></Field></div></section>
    <section className="form-card"><h2 className="form-heading">Fasting & meals</h2><div className="grid gap-4 sm:grid-cols-3"><Field label="Eating window starts"><input type="time" value={form.eatingWindowStart} onChange={(e) => update('eatingWindowStart', e.target.value)} /></Field><Field label="Eating window ends"><input type="time" value={form.eatingWindowEnd} onChange={(e) => update('eatingWindowEnd', e.target.value)} /></Field><Field label="Fasting hours"><input type="number" min="0" max="36" step="0.5" value={form.fastingHours ?? ''} onChange={(e) => update('fastingHours', toNum(e.target.value))} placeholder="16" /></Field><Field label="First meal" wide><textarea value={form.firstMeal} onChange={(e) => update('firstMeal', e.target.value)} placeholder="Example: eggs, chicken, salad" /></Field><Field label="Second meal" wide><textarea value={form.secondMeal} onChange={(e) => update('secondMeal', e.target.value)} placeholder="Example: salmon, vegetables, Greek yogurt" /></Field></div></section>
    <section className="form-card"><h2 className="form-heading">Food choices</h2><div className="grid gap-4 sm:grid-cols-2"><Toggle label="Any snacks?" checked={form.snacks} onChange={(v) => update('snacks', v)} /><Toggle label="Any late-night eating?" checked={form.lateNightEating} onChange={(v) => update('lateNightEating', v)} /><Toggle label="Any sugary drink?" checked={form.sugaryDrink} onChange={(v) => update('sugaryDrink', v)} /><Field label="Refined carbs"><select value={form.refinedCarbs} onChange={(e) => update('refinedCarbs', e.target.value as RefinedCarbs)}><option value="none">None</option><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select></Field></div></section>
    <section className="form-card"><h2 className="form-heading">Body & mood</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><Field label="Exercise type"><input value={form.exerciseType} onChange={(e) => update('exerciseType', e.target.value)} placeholder="Walking, strength..." /></Field><Field label="Exercise minutes"><input type="number" min="0" max="600" value={form.exerciseMinutes ?? ''} onChange={(e) => update('exerciseMinutes', toNum(e.target.value))} /></Field><Field label="Sleep hours"><input type="number" min="0" max="24" step="0.5" value={form.sleepHours ?? ''} onChange={(e) => update('sleepHours', toNum(e.target.value))} /></Field><RangeField label="Hunger level" value={form.hungerLevel} onChange={(v) => update('hungerLevel', v)} /><RangeField label="Energy level" value={form.energyLevel} onChange={(v) => update('energyLevel', v)} /><RangeField label="Mood" value={form.moodLevel} onChange={(v) => update('moodLevel', v)} /></div></section>
    <section className="form-card"><h2 className="form-heading">Reflection</h2><div className="grid gap-4 sm:grid-cols-2"><Field label="Biggest problem today"><textarea value={form.biggestProblem} onChange={(e) => update('biggestProblem', e.target.value)} /></Field><Field label="Tomorrow’s focus"><textarea value={form.tomorrowFocus} onChange={(e) => update('tomorrowFocus', e.target.value)} /></Field><Field label="Notes" wide><textarea rows={4} value={form.notes} onChange={(e) => update('notes', e.target.value)} /></Field></div></section>
    <button className="btn w-full sm:w-auto" type="submit">Save today</button>
  </form>{messages.length > 0 && <section className="mt-5 space-y-2">{messages.map((m, i) => <div key={i} className={`rounded-xl border px-4 py-3 text-sm ${m.kind === 'good' ? 'border-emerald-200 bg-emerald-50 text-emerald-900' : 'border-amber-200 bg-amber-50 text-amber-900'}`}>{m.kind === 'good' ? '✓ ' : '!' }{m.text}</div>)}</section>}</>
}
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (v: boolean) => void }) { return <div><span className="field-label">{label}</span><div className="flex rounded-lg border border-slate-300 p-1"><button type="button" onClick={() => onChange(false)} className={`flex-1 rounded-md py-2 text-sm font-medium ${!checked ? 'bg-emerald-700 text-white' : 'text-slate-600'}`}>No</button><button type="button" onClick={() => onChange(true)} className={`flex-1 rounded-md py-2 text-sm font-medium ${checked ? 'bg-amber-500 text-white' : 'text-slate-600'}`}>Yes</button></div></div> }
function RangeField({ label, value, onChange }: { label: string; value: number | null; onChange: (v: number | null) => void }) { return <label><span className="field-label">{label}: <b>{value ?? '—'}</b></span><input className="range" type="range" min="1" max="10" value={value ?? 5} onChange={(e) => onChange(Number(e.target.value))} /><div className="flex justify-between text-xs text-slate-400"><span>1</span><span>10</span></div></label> }

function History({ logs, settings, onEdit, onDelete, onImport }: { logs: DailyLog[]; settings: AppSettings; onEdit: (l: DailyLog) => void; onDelete: (id: string) => Promise<void>; onImport: (logs: DailyLog[], mode: 'merge' | 'replace', settings?: AppSettings) => Promise<void> }) {
  const [query, setQuery] = useState(''); const [period, setPeriod] = useState<'all' | 'week' | 'month'>('all'); const [selected, setSelected] = useState<string[]>([]); const fileRef = useRef<HTMLInputElement>(null)
  const now = new Date(); const cutoff = period === 'week' ? dateKey(addDays(now, -6)) : dateKey(addDays(now, -29)); const shown = logs.filter((l) => (period === 'all' || l.date >= cutoff) && l.date.includes(query))
  const choose = (id: string) => setSelected((old) => old.includes(id) ? old.filter((x) => x !== id) : [...old, id])
  const exportData = (kind: 'csv' | 'json') => { const rows = selected.length ? logs.filter((l) => selected.includes(l.id)) : logs; if (kind === 'json') download(`weight-path-${dateKey(new Date())}.json`, 'application/json', JSON.stringify(backup(settings, rows), null, 2)); else download(`weight-path-${dateKey(new Date())}.csv`, 'text/csv', [csvColumns.join(','), ...rows.map((r) => csvColumns.map((key) => csvValue(r[key])).join(','))].join('\n')) }
  const parseImport = async (file: File) => { try { const text = await file.text(); let entries: DailyLog[] = []; let incoming: AppSettings | undefined; if (file.name.toLowerCase().endsWith('.json')) { const data = JSON.parse(text); if (!Array.isArray(data.logs)) throw new Error('This JSON backup does not contain logs.'); entries = data.logs; incoming = data.settings } else { const [headerRow, ...csvRows] = parseCsv(text); const headers = headerRow ?? []; entries = csvRows.filter((values) => values.some(Boolean)).map((values) => { const row = Object.fromEntries(headers.map((h, i) => [h, values[i] ?? ''])); const log = emptyLog(row.date); Object.assign(log, row, { weightKg: toNum(row.weightKg), fastingHours: toNum(row.fastingHours), exerciseMinutes: toNum(row.exerciseMinutes), sleepHours: toNum(row.sleepHours), hungerLevel: toNum(row.hungerLevel), energyLevel: toNum(row.energyLevel), moodLevel: toNum(row.moodLevel), snacks: row.snacks === 'true', lateNightEating: row.lateNightEating === 'true', sugaryDrink: row.sugaryDrink === 'true', refinedCarbs: (['none','low','medium','high'].includes(row.refinedCarbs) ? row.refinedCarbs : 'none') as RefinedCarbs }); return log }) }
    if (!entries.length || entries.some((l) => !/^\d{4}-\d{2}-\d{2}$/.test(l.date))) throw new Error('No valid dated records were found.'); const mode = window.confirm(`Import ${entries.length} records?\n\nPress OK to merge (imported dates replace matching local dates). Press Cancel for replace mode.`) ? 'merge' : 'replace'; if (mode === 'replace' && !window.confirm('Replace clears your current logs. Continue?')) return; await onImport(entries, mode, incoming) } catch (e) { window.alert(e instanceof Error ? e.message : 'Could not import that file.') } finally { if (fileRef.current) fileRef.current.value = '' } }
  return <><SectionTitle title="History" subtitle="Search, edit, back up, or restore your daily records." action={<div className="flex gap-2"><button className="btn-secondary" onClick={() => fileRef.current?.click()}>Import</button><input ref={fileRef} className="hidden" type="file" accept=".json,.csv,application/json,text/csv" onChange={(e) => e.target.files?.[0] && parseImport(e.target.files[0])} /></div>} /><div className="mb-4 flex flex-wrap gap-2"><input className="max-w-xs" placeholder="Search date (YYYY-MM-DD)" value={query} onChange={(e) => setQuery(e.target.value)} />{(['all','week','month'] as const).map((item) => <button key={item} className={`filter ${period === item ? 'filter-active' : ''}`} onClick={() => setPeriod(item)}>{item === 'all' ? 'All time' : `Last ${item}`}</button>)}<span className="ml-auto self-center text-sm text-slate-500">{selected.length ? `${selected.length} selected` : `${shown.length} records`}</span></div><div className="mb-4 flex gap-2"><button className="btn-secondary" disabled={!logs.length} onClick={() => exportData('csv')}>Export CSV</button><button className="btn-secondary" disabled={!logs.length} onClick={() => exportData('json')}>Export JSON</button></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table><thead><tr><th><input type="checkbox" checked={shown.length > 0 && shown.every((l) => selected.includes(l.id))} onChange={(e) => setSelected(e.target.checked ? [...new Set([...selected, ...shown.map((l) => l.id)])] : selected.filter((id) => !shown.some((l) => l.id === id)))} /></th><th>Date</th><th>Weight</th><th>Fast</th><th>Food flags</th><th>Exercise</th><th></th></tr></thead><tbody>{shown.map((log) => <tr key={log.id}><td><input type="checkbox" checked={selected.includes(log.id)} onChange={() => choose(log.id)} /></td><td className="font-medium">{fmtDate(log.date)}</td><td>{log.weightKg == null ? '—' : `${fmtNum(log.weightKg)} kg`}</td><td>{log.fastingHours == null ? '—' : `${fmtNum(log.fastingHours)} h`}</td><td>{[log.sugaryDrink && 'Sugar', log.snacks && 'Snacks', log.lateNightEating && 'Late'].filter(Boolean).join(', ') || 'Clear'}</td><td>{log.exerciseMinutes ? `${log.exerciseMinutes} min` : '—'}</td><td className="whitespace-nowrap"><button className="link" onClick={() => onEdit(log)}>Edit</button><button className="link danger" onClick={() => onDelete(log.id)}>Delete</button></td></tr>)}{!shown.length && <tr><td colSpan={7} className="py-10 text-center text-slate-500">No daily logs found.</td></tr>}</tbody></table></div></div></>
}
function parseCsv(text: string) { const rows: string[][] = []; let row: string[] = []; let value = ''; let quoted = false; for (let i = 0; i < text.length; i++) { const char = text[i]; if (char === '"') { if (quoted && text[i + 1] === '"') { value += '"'; i++ } else quoted = !quoted } else if (char === ',' && !quoted) { row.push(value); value = '' } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[i + 1] === '\n') i++; row.push(value); rows.push(row); row = []; value = '' } else value += char } if (value || row.length) { row.push(value); rows.push(row) } return rows }

function WeeklyReview({ logs, settings }: { logs: DailyLog[]; settings: AppSettings }) { const starts = [...new Set(logs.map((l) => dateKey(weekStart(dateFromKey(l.date)))))] .sort().reverse(); const [selected, setSelected] = useState(starts[0] ?? dateKey(weekStart(new Date()))); useEffect(() => { if (starts[0] && !starts.includes(selected)) setSelected(starts[0]) }, [logs])
  const from = dateFromKey(selected); const until = dateKey(addDays(from, 6)); const weekly = logs.filter((l) => l.date >= selected && l.date <= until); const prevStart = dateKey(addDays(from, -7)); const prev = logs.filter((l) => l.date >= prevStart && l.date < selected); const avgWeight = average(weekly.map((l) => l.weightKg)); const previousWeight = average(prev.map((l) => l.weightKg)); const exercises = weekly.reduce((sum, l) => sum + (l.exerciseMinutes ?? 0), 0); const goal = fastingGoal(settings)
  const weekAverages = starts.map((start) => average(logs.filter((l) => l.date >= start && l.date <= dateKey(addDays(dateFromKey(start), 6))).map((l) => l.weightKg))).filter((v): v is number => v != null).reverse(); const plateau = weekAverages.length >= 4 && weekAverages.slice(-4).every((v, i, list) => i === 0 || list[i - 1] - v < .1)
  const suggestions = [plateau && 'Weight has not dropped meaningfully for three weeks. Check sugar, snacks, refined carbs, and weekend overeating.', average(weekly.map((l) => l.hungerLevel)) != null && average(weekly.map((l) => l.hungerLevel))! >= 7 && 'High hunger: increase protein and vegetables at meals.', average(weekly.map((l) => l.sleepHours)) != null && average(weekly.map((l) => l.sleepHours))! < 7 && 'Low sleep can make hunger worse. Aim for a steadier bedtime.', exercises < 100 && 'Exercise was low this week. Try walking 20–40 minutes most days.', !plateau && exercises >= 100 && 'Keep the routine simple and repeat what worked this week.'].filter(Boolean) as string[]
  return <><SectionTitle title="Weekly review" subtitle="Automatic patterns and a simple next step." action={<select className="w-auto" value={selected} onChange={(e) => setSelected(e.target.value)}>{(starts.length ? starts : [selected]).map((s) => <option key={s} value={s}>Week of {fmtDate(s)}</option>)}</select>} /><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{fmtDate(selected)} – {fmtDate(until)}</p><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4"><Stat label="Average weight" value={`${fmtNum(avgWeight)} kg`} /><Stat label="Weekly change" value={avgWeight != null && previousWeight != null ? `${avgWeight - previousWeight > 0 ? '+' : ''}${fmtNum(avgWeight - previousWeight)} kg` : '—'} /><Stat label="Average fast" value={`${fmtNum(average(weekly.map((l) => l.fastingHours)))} h`} hint={`Goal: ${goal}+h`} /><Stat label="Exercise" value={`${exercises} min`} /></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><Mini label="Sugary drinks" value={weekly.filter((l) => l.sugaryDrink).length} /><Mini label="Snack days" value={weekly.filter((l) => l.snacks).length} /><Mini label="Late eating days" value={weekly.filter((l) => l.lateNightEating).length} /><Mini label="Average hunger" value={fmtNum(average(weekly.map((l) => l.hungerLevel)))} /><Mini label="Average sleep" value={`${fmtNum(average(weekly.map((l) => l.sleepHours)))} h`} /><Mini label="Logged days" value={weekly.length} /></div></div><section className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Suggested focus for next week</h2><ul className="mt-3 space-y-2 text-sm text-amber-900">{suggestions.map((item) => <li key={item}>• {item}</li>)}</ul></section></> }
function Mini({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-lg font-bold">{value}</p></div> }

function Plan({ settings, onSettings }: { settings: AppSettings; onSettings: (s: AppSettings) => Promise<void> }) { const month = planMonth(settings.planStartDate); const stages = [{ title: 'Month 1', range: '111 kg to 108–109 kg', fast: '12:12 to 14:10', focus: 'Stop sugary drinks, stop snacks, stop late-night eating', active: month === 1 }, { title: 'Months 2–3', range: '103–105 kg', fast: '16:8 to 18:6', focus: 'Two meals per day, eating window around 12:00–18:00', active: month >= 2 && month <= 3 }, { title: 'Months 4–6', range: '97–100 kg', fast: '18:6 most days', focus: 'Consistency, protein, vegetables, walking, strength training', active: month >= 4 && month <= 6 }, { title: 'Months 7–9', range: '94–97 kg', fast: '18:6, optional occasional 20:4', focus: 'Handle plateau, avoid hidden carbs and snacks', active: month >= 7 && month <= 9 }, { title: 'Months 10–12', range: '92–96 kg', fast: 'Stable long-term 18:6 or 16:8', focus: 'Prevent rebound and build lifestyle habits', active: month >= 10 }]; return <><SectionTitle title="Your 1-year plan" subtitle={`You are in month ${month} of your plan.`} /><div className="mb-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><label className="field-label">Plan start date</label><input className="max-w-xs" type="date" value={settings.planStartDate} onChange={(e) => void onSettings({ ...settings, planStartDate: e.target.value })} /><p className="mt-2 text-xs text-slate-500">This date controls the current plan stage and fasting goal.</p></div><div className="space-y-3">{stages.map((stage) => <article key={stage.title} className={`rounded-2xl border p-5 ${stage.active ? 'border-emerald-500 bg-emerald-50 shadow-sm' : 'border-slate-200 bg-white'}`}><div className="flex items-center justify-between"><h2 className="font-bold">{stage.title}</h2>{stage.active && <span className="rounded-full bg-emerald-700 px-2.5 py-1 text-xs font-semibold text-white">Current stage</span>}</div><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div><dt className="text-slate-500">Goal</dt><dd className="font-medium">{stage.range}</dd></div><div><dt className="text-slate-500">Fasting</dt><dd className="font-medium">{stage.fast}</dd></div><div><dt className="text-slate-500">Focus</dt><dd className="font-medium">{stage.focus}</dd></div></dl></article>)}</div></> }
function Rules() { const good = ['Eggs', 'Meat', 'Fish', 'Chicken', 'Beef', 'Lamb', 'Tofu', 'Vegetables', 'Greek yogurt without sugar', 'Nuts in small amounts', 'Olive oil', 'Avocado']; const reduce = ['Sugary drinks', 'Juice', 'Bubble tea', 'Desserts', 'Cookies', 'Cakes', 'White bread', 'Noodles', 'Pasta', 'White rice', 'Potatoes', 'Chips', 'Late-night snacks']; const rules = ['No sugary drinks', 'No snacks if possible', 'No eating after the eating window', 'Eat enough protein', 'Eat many vegetables', 'Walk daily', 'Track honestly, not perfectly']; return <><SectionTitle title="Simple food rules" subtitle="Keep meals satisfying and choices uncomplicated." /><div className="grid gap-5 md:grid-cols-2"><FoodList title="Good foods" items={good} tone="green" /><FoodList title="Avoid or reduce" items={reduce} tone="amber" /></div><section className="mt-5 rounded-2xl bg-emerald-800 p-6 text-white"><h2 className="text-lg font-bold">Main rules</h2><ul className="mt-4 grid gap-3 sm:grid-cols-2">{rules.map((rule) => <li key={rule} className="rounded-lg bg-white/10 px-3 py-2 text-sm">✓ {rule}</li>)}</ul></section></> }
function FoodList({ title, items, tone }: { title: string; items: string[]; tone: 'green' | 'amber' }) { return <section className={`rounded-2xl border p-5 ${tone === 'green' ? 'border-emerald-200 bg-emerald-50' : 'border-amber-200 bg-amber-50'}`}><h2 className="font-bold">{title}</h2><ul className="mt-3 grid grid-cols-2 gap-2 text-sm">{items.map((item) => <li key={item}>• {item}</li>)}</ul></section> }

export default App
